---

# Example playbook for your project. 
#
# Update the roles_path to be relative from your project,
# e.g. roles_path: "../ansible-provisioner/roles"

- hosts: all
  vars:
    env: development
    app_public: "/var/www"
    roles_path: 'roles'

  roles:
    - "{{roles_path}}/init"
    - "{{roles_path}}/nodejs"
    - "{{roles_path}}/python-tools"
    - "{{roles_path}}/mongodb"
    - "{{roles_path}}/nginx"
